.PHONY: all
all:

.PHONY: clean
clean:
	make -C VecAdd clean
	make -C Histogram clean
	make -C Transpose clean
	make -C Reduce clean
	make -C Scan clean
	make -C MatVecMul clean
	make -C MatMul clean
	make -C BitonicSortSmall clean
	make -C BitonicSortLarge clean
	make -C SparseMatVecMul clean
	make -C OverlappingVecAdd clean
	make -C OverlappingTranspose clean
	make -C OverlappingKernels clean
	make -C NonOverlappingShared clean
	make -C TwoKernels clean
	make -C OverlappingSparseMatVecMul clean
	make -C OverlappingZeroing clean
	make -C MaliciousAttack clean
	make -C OverlappingReduce clean
